### ISSUE TITLE
Documentation for Interface

### ISSUE THREAD

**Issue by nsoblath** [driplineorg/dripline-python#103]
One of the arguments for the `__init__()` function of the Interface class is the `dripline_config` object.  While the available parameters can be determined with some work (e.g. looking at the final config output when running dl-agent, or looking in `dl-cpp::dripline_config`), we should instead add some documentation somewhere about what values can be used.

I'm not sure this is the right place for it, but I'm leaving this issue here because the Interface class is an obvious place where this would be useful to a dl-python client.  However, this object configures `dl-cpp::core`, so maybe the documentation belongs in dl-cpp with links from other places.

**Comment by laroque** [comment]
Yeah I think that's right. The pattern is to accept a config object without parsing/constructing that object so that if `dl-cpp::core` ever changes what's in the config, that is transparent here. We should at least link out to the dl-cpp build results. For bonus points the sphinx autodoc could probably extract that unit from the doxygen XML and populate the object right in the dripline python docs. ... that sounds super slick, but I dunno who/when there'll be time to do it.

**Comment by nsoblath** [comment]
This is taken care of in the auth branch.
