### ISSUE TITLE
Fix Unit Tests

### ISSUE THREAD

**Issue by allgoodpnw** [driplineorg/dripline-python#176]
### Overview

Currently, unit tests are failing the following cases in the following MR: https://github.com/driplineorg/dripline-python/actions/runs/10967365307/job/30456999666:
=========================== short test summary info ============================
FAILED test_constants.py::test_op_t_string_to_op_t - Exception: unable to map...
FAILED test_constants.py::test_msg_t_string_to_msg_t - Exception: unable to m...
FAILED test_endpoint.py::test_submit_request_message - assert 310 == 0
FAILED test_endpoint.py::test_on_request_message - assert 310 == 0
FAILED test_endpoint.py::test_on_reply_message - Exception: Base endpoint doe...
FAILED test_endpoint.py::test_on_alert_message - Exception: Base endpoint doe...
FAILED test_endpoint.py::test_do_get_request_valid_specifier - dripline.core....
FAILED test_endpoint.py::test_do_set_request_no_specifier - AttributeError: '...
FAILED test_endpoint.py::test_do_set_request_invalid_specifier - AttributeErr...
FAILED test_endpoint.py::test_do_set_request_valid_specifier - AttributeError...
FAILED test_endpoint.py::test_do_cmd_request_valid_specifier - AttributeError...
=================== 11 failed, 27 passed, 1 warning in 0.58s ===================

### Goal
- Find out why there weren't unit tests in main and develop branch
- Find out why MR from integration_test to develop 5 months ago failed
- Find out where unit tests came from within the feature/http_with_auth branch
- Find out why unit tests are breaking
- Fix issues

**Comment by allgoodpnw** [comment]
@nsoblath any additional context would be helpful. I notice in the develop branch there is a failed cicd pipeline from the `feature/integration_test` branch, is there anything about that failed pipeline that might be useful here? Also, I notice that the develop branch was never set up to run unit tests in the cicd pipeline? Maybe I overlooked something but if that's the case im curious if the `http_with_auth` is actually a `http_with_auth_and_unit_test` branch

**Comment by nsoblath** [comment]
@allgoodpnw I see what you're saying about the failure when `integration_tests` was merged into `develop`.  I'm not sure I had seen that that had happened.  It looks like it happened in the second set of jobs, where the docker images that are pushed to GHCR are built.  In that case it was passing the unit tests, which are run in the first CICD job.

Prior to my adding the integration tests, there were some unit tests written, but coverage was poor, and it wasn't a part of the CICD.  I added it to the GHA workflow in the `integration_tests` branch, and when I merged that into `develop`, the running of unit tests came with it.  At that point, the unit tests did run and passed (see this [log](https://github.com/driplineorg/dripline-python/actions/runs/9704976431/job/26786203829)).

**Comment by nsoblath** [comment]
@allgoodpnw I see two types of errors occurring in the pytest functions:
1. It looks like I was attempting to use a pattern where an exception would be thrown and caught within the test.  But the exceptions are causing the tests to fail instead.
2. There's some problem with objects getting added to nodes.

I believe I know how to fix problem 2.  The `=` operator doesn't work on scarab.ParamNode for adding something to the structure.  It's actually producing behavior that's unexpected, which isn't good; it should either be made to work or fail in a useful way.  I'll deal with that in the scarab repo at another time.  For now, though, the behavior can be worked around in dl-py.

Instead of using `=` to add something to the node, you can use `add()` (won't add if the key already exists) or `replace()` (will replace what's there if the key already exists).  e.g. test_endpoint.py line 82 should be `the_node.add("values", scarab.ParamArray())`.

It looks like endpoint.py also has the same bug, at least at line 50, which should be `the_node.add("values", scarab.ParamArray())`.

**Comment by allgoodpnw** [comment]
looking more into this, i notice that some of the errors from the unit tests throw an AttributeError saying that scarab doesnt have `push_back` but it looks like that shouldnt be the case according to this header file in the scarab utitility repo: https://github.com/project8/scarab/blob/main/python/param_node_pybind.hh

**Comment by nsoblath** [comment]
This should be solved by using `add()` or `replace()` instead of assignment (i.e. `=`).  When assignment is used, the wrong type is being added to the node: `Param` instead of `ParamArray`.  `Param` does not have `push_back()`, hence the AttributeError.  If you use `add()` or `replace()`, it'll actually put a `ParamArray` in the node, so `push_back()` will work.

**Comment by allgoodpnw** [comment]
TODO: pybind11 in c++ translates dripline errors into generic Exception error in Python. so right now the unit tests contain a catch all exception
